### ISSUE TITLE
Data not updating?

### ISSUE THREAD

**Issue by peterwc-cdc** [corneliusroemer/pango-sequences#5]
**Current Behavior**  
A clear and concise description of what is happening / what the bug is.  
Normally the data for the consensus files are regularly updated, but currently there have been no changes in several weeks.

**Expected behavior**  
A clear and concise description of what you expected to happen instead.  
The data had some automated updates (or semi-automated) that occurred as new lineages were produced. 
**How to reproduce**  
Steps to reproduce the current behavior:  
1. git pull
4. See error  - ie no changes to repo

**Possible solution**  
Is there a different repo? Is this something that others can help with developing and implementing?

**Your environment: if browsing Nextstrain online**  
 - Operating system:  
 - Browser:  

**Your environment: if running Nextstrain locally**  
 - Operating system:   
 - Browser:  
 - Version (e.g. `auspice 2.7.0`):  

**Additional context**

**Comment by corneliusroemer** [comment]
Thanks for opening this issue (and closing)! Sorry for the delay in responding, I'd definitely appreciate similar issues in the future

**Comment by peterwc-cdc** [comment]
No worries! Will do! You got to it and this code base and data has been excellent!
________________________________
